name: CI Multi-Jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Simuler un build
        run: |
          echo "Compilation du projet..."
          mkdir -p output # Créer le dossier output
          echo "Résultat du build" > output/build_result.txt

      - name: Uploader l'artefact du build
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/

  test:
    runs-on: ubuntu-latest
    needs: build # Dépend du job 'build'
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Télécharger l'artefact du build
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: downloaded_build_output

      - name: Simuler des tests
        run: |
          echo "Exécution des tests sur le résultat du build..."
          cat downloaded_build_output/build_result.txt
          echo "Tests terminés !"

  deploy:
    runs-on: ubuntu-latest
    needs: test # Dépend du job 'test'
    if: github.ref == 'refs/heads/main' # Vérifie que le job s'exécute seulement sur la branche 'main'
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Simuler un déploiement
        run: echo "Déploiement du projet..."

