name: CI avec Matrice Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20'] # Tu peux ajouter d'autres versions ici

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Afficher la version de Node.js
        run: echo "Test avec Node.js $(node -v) sur ${{ runner.os }}"
