name: CI Simple

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world depuis GitHub Actions !"
